[tool.pytest.ini_options]
addopts = "--cov=timm --cov-report=term-missing"
markers = [
    "base: marker for model tests using the basic setup",
    "cfg: marker for model tests checking the config",
    "torchscript: marker for model tests using torchscript",
    "features: marker for model tests checking feature extraction",
    "fx: marker for model tests using torch fx",
]

[tool.coverage.run]
omit = [
    "tests/test_*.py",
]

[tool.black]
line-length = 120
target-version = ['py37', 'py38', 'py39', 'py310', 'py311']
skip-string-normalization = true
